name = "Falcons"
uuid = "eba0fb4b-2daf-4740-90d2-e5655143e0a0"
authors = ["Yusuke Takase"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
